Fix Android read-only error
benwiley4000/react-extra-prop-types pull request #2
Opened 2017-07-16 14:52 UTC by ixje

https://github.com/benwiley4000/react-extra-prop-types/issues/1

2017-07-16 15:34 UTC, benwiley4000 requested changes
Looks great - thanks for catching this. Just a couple tiny style/formatting changes.

Also, looks like you're not committing with your GitHub email, so the commits won't be attributed to your account - in case that matters to you! Feel free to force push if you want to [update those commits with new info](https://gist.github.com/trey/9588090).

2017-07-16 15:34 UTC, benwiley4000 commented on lib/createPropType.js
> +  }
Total nit, but could we get a semicolon, and a newline after the `catch`? Thanks! 🙂

2017-07-17 12:53 UTC, ixje commented
I hope that should do it :)

2017-07-17 14:15 UTC, benwiley4000 commented
Haha sorry, should have been more obvious; the semicolon goes at the end of the `Object.defineProperty(...)` call, not the catch 😬

2017-07-17 15:43 UTC, ixje commented
Hehe no worries, there are so many coding styles that I didn't even think about whether it made sense or not.

2017-07-17 16:54 UTC, benwiley4000 approved these changes

2017-07-17 16:54 UTC, benwiley4000 commented
Thanks! 😄

2017-07-17 16:54 UTC, merged

2017-07-17 17:00 UTC, benwiley4000 commented
Published to npm, v0.3.1. 🎉